spring:
  application:
    name: facility-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: default_user_66m1znNBWhzukr0ncY7
    password: nmg9O-oVV0N12V2-cUqCaSeDZUVP6NMC

  #NO DOCKER : jdbc:postgresql://localhost:5432/facility
  #CON DOCKER: jdbc:postgresql://dbfacility:5432/facility
  datasource:
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://dbfacility:5432/facility
    password: asd

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

server:
  port: '8086'

xchange:
  name: roytuts.rpc

queue:
  name: roytuts.rpc.queue


rabbit:
  facility:
    exchange-name: rpc.facility
    hours:
      queue-name: rpc.facility.hours
      key: facility.hours
    sports:
      queue-name: rpc.facility.sports
      key: facility.sports

session:
  datasource:
    #NO DOCKER : jdbc:postgresql://localhost:5432/session
    #CON DOCKER: jdbc:postgresql://dbsession:5432/session
    url: jdbc:postgresql://dbsession:5432/session
    driver-class-name: org.postgresql.Driver
    username: taass
    password: asd

    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false

      # Because detection is disabled you have to set correct dialect by hand.
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate:
        ddl-auto: update

eureka:
  instance:
    # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
    preferIpAddress: true
    # The hostname of the service, to register the pod and turn it easier for the gateway to find it
    hostname: facility-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:8761/eureka

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:eureka:8761/eureka
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:eureka:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:eureka:8761/eureka
