spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://localhost:5432/facility
    password: asd
  application:
    name: facility-service
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

server:
  port: '8086'

xchange:
  name: roytuts.rpc

queue:
  name: roytuts.rpc.queue


rabbit:
  facility:
    exchange-name: rpc.facility
    hours:
      queue-name: rpc.facility.hours
      key: facility.hours
    sports:
      queue-name: rpc.facility.sports
      key: facility.sports

