apiVersion: v1
kind: Service
metadata:
  name: facility-service
spec:
  type: ClusterIP
  selector:
    app: facility-service
  ports:
    - port: 8086
      targetPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: facility-service-np
spec:
  type: NodePort
  selector:
    app: facility-service
  ports:
    - port: 8086
      targetPort: 8086

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facility-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facility-service
  template:
    metadata:
      labels:
        app: facility-service
    spec:
      containers:
        - name: facility
          image: facility-server #bisogna usare la propria immagine nel proprio repository
          imagePullPolicy: "IfNotPresent"
      restartPolicy: Always
