version: '3'

services:
  dbreservations:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: peppe
      POSTGRES_PASSWORD: asd
      restart: unless-stopped
  app:
    build: .
    image: reservations-service
    container_name: reservations-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbreservations:5432/reservations
      - SPRING_DATASOURCE_USERNAME=peppe
      - SPRING_DATASOURCE_PASSWORD=asd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8083:8083"
    depends_on:
      - dbreservations

