eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: zuul-service

#forse e' inutile
ribbon:
  eureka:
    enabled: false

server:
  port: 8080

#per provare con intellij sostituire "***-service" nell'url con "localhost"
zuul:
  routes:
    reservation-service:
      path: /reservations/**
      url: http://reservation-service:8083/api/v1/reservations/
      service-id: reservation-service
    lesson-service:
      url: http://lesson-service:8082/api/v1/lessons/
      path: /lessons/**
      service-id: lesson-service
    tournament-service:
      path: /tournaments/**
      service-id: tournament-service
      url: http://tournament-service:8084/api/v1/tournaments/
    reservation-service2:
      url: http://reservation-service:8083/api/v1/courts/
      service-id: reservation-service2
      path: /courts/**
    board-service:
      url: http://board-service:8081/api/v1/boards/
      path: /boards/**
      service-id: board-service
    user-service:
      url: http://user-service:8085/api/v1/users/
      service-id: user-service
      path: /users/**