eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #prima era settato a true
    fetch-registry: false #prima era settato a true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: zuul-service

#forse e' inutile
ribbon:
  eureka:
    enabled: false

server:
  port: 8080

#con intellij utilizzare localhost:port nell'url
#con docker utilizzare ***-service:port nell'url
zuul:
  routes:
    reservation-service:
      path: /reservations/**
      url: http://localhost:8083/api/v1/reservations/
      service-id: reservation-service
    lesson-service:
      url: http://localhost:8082/api/v1/lessons/
      path: /lessons/**
      service-id: lesson-service
    tournament-service:
      path: /tournaments/**
      service-id: tournament-service
      url: http://localhost:8084/api/v1/tournaments/
    reservation-service2:
      url: http://localhost:8083/api/v1/courts/
      service-id: reservation-service2
      path: /courts/**
    board-service:
      url: http://localhost:8081/api/v1/boards/
      path: /boards/**
      service-id: board-service
    user-service:
      url: http://localhost:8085/api/v1/users/
      service-id: user-service
      path: /users/**