apiVersion: v1
kind: Service
metadata:
  name: lesson-service
spec:
  type: ClusterIP
  selector:
    app: lesson-service
  ports:
    - port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesson-service
  template:
    metadata:
      labels:
        app: lesson-service
    spec:
      containers:
        - name: lesson-service
          image: lesson-service #bisogna usare la propria immagine nel proprio repository
          imagePullPolicy: "IfNotPresent"
      restartPolicy: Always
