kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-lesson-pv-volume
  labels:
    type: local
    app: dblessons
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-lesson-pv-claim
  labels:
    app: dblessons
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
