spring:
  application:
    name: zuul-server

server:
  port: 8080

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

#ribbon:
#  eureka:
#    enabled: true
---
#spring:
#  profiles: docker

#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-discovery:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    tournament-service: /api/v1/tournaments/**
    reservation-service: /api/v1/reservations/**
    board-service: /api/v1/boards/**
    lesson-service: /api/v1/lessons/**
    user-service: /api/v1/users/**
    facility-service: /api/v1/facility/**
    frontend:
      path: /**
      url: http://localhost:4200/

#taass:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpirationMsec: 864000000
#  routes:
#    tournaments-service: /myusers/**