version: '3'

services:
  dbtournaments:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tournaments
      POSTGRES_USER: peppe
      POSTGRES_PASSWORD: asd
      restart: unless-stopped
  app:
    build: .
    image: tournaments-service
    container_name: tournaments-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbtournaments:5432/tournaments
      - SPRING_DATASOURCE_USERNAME=peppe
      - SPRING_DATASOURCE_PASSWORD=asd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8084:8084"
    depends_on:
      - dbtournaments

