spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://localhost:5432/reservations
    password: asd
  application:
    name: reservation-service
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
server:
  port: '8083'