spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://localhost:5432/boards
    password: asd
  application:
    name: board-service
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
server:
  port: '8081'

rabbit:
  facility:
    exchange-name: rpc.facility
    hours:
      queue-name: rpc.facility.hours
      key: facility.hours