version: '3'

services:
  dbusers:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: peppe
      POSTGRES_PASSWORD: asd
      restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: users-service
    container_name: users-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbusers:5432/users
      - SPRING_DATASOURCE_USERNAME=peppe
      - SPRING_DATASOURCE_PASSWORD=asd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8085:8085"
    depends_on:
      - dbusers

