spring:

  application:
    name: lesson-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: default_user_66m1znNBWhzukr0ncY7
    password: nmg9O-oVV0N12V2-cUqCaSeDZUVP6NMC

  datasource:
    #NO DOCKER : jdbc:postgresql://localhost:5432/lessons
    #CON DOCKER: jdbc:postgresql://dblessons:5432/lessons
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://dblessons:5432/lessons
    password: asd

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

server:
  port: '8082'

session:
  datasource:
    #NO DOCKER : jdbc:postgresql://localhost:5432/session
    #CON DOCKER: jdbc:postgresql://dbsession:5432/session
    url: jdbc:postgresql://dbsession:5432/session
    driver-class-name: org.postgresql.Driver
    username: taass
    password: asd

    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false

      # Because detection is disabled you have to set correct dialect by hand.
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate:
        ddl-auto: update

rabbit:
  courses:
    exchange-name: rpc.courses
    upcoming:
      queue-name: rpc.courses.upcoming
      key: courses.upcoming

  facility:
    exchange-name: rpc.facility
    hours:
      key: facility.hours
    sports:
      key: facility.sports

  reservation:
    exchange-name: rpc.reservation
    reserve:
      key: reservation.reserve
    delete:
      key: reservation.delete

eureka:
  instance:
    # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
    preferIpAddress: true
    # The hostname of the service, to register the pod and turn it easier for the gateway to find it
    hostname: lesson-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-2.eureka.default.svc.cluster.local:8761/eureka