spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: taass
    url: jdbc:postgresql://localhost:5432/lessons
    password: asd

  application:
    name: lesson-service

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

server:
  port: '8082'

session:
  datasource:
    url: jdbc:postgresql://localhost:5432/session
    driver-class-name: org.postgresql.Driver
    username: taass
    password: asd

    jpa:
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false

      # Because detection is disabled you have to set correct dialect by hand.
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate:
        ddl-auto: update

rabbit:
  courses:
    exchange-name: rpc.courses
    upcoming:
      queue-name: rpc.courses.upcoming
      key: courses.upcoming

  facility:
    exchange-name: rpc.facility
    hours:
      key: facility.hours
    sports:
      key: facility.sports

  reservation:
    exchange-name: rpc.reservation
    reserve:
      key: reservation.reserve
    delete:
      key: reservation.delete
