version: '3'

services:
  dbboards:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: peppe
      POSTGRES_PASSWORD: asd
      restart: unless-stopped
  app:
    build: .
    image: boards-service
    container_name: boards-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbboards:5432/boards
      - SPRING_DATASOURCE_USERNAME=peppe
      - SPRING_DATASOURCE_PASSWORD=asd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    depends_on:
      - dbboards

